### PR TITLE
Podspec fixes

### PR DESCRIPTION
**Pull request by cristiankocza-sv**
Fixed library and framework reference.

### CODE REVIEW

**Comment by kostiadombrovsky** [comment]
@indutny could you please take a look? We need this for iOS 9.

**Comment by indutny** [comment]
LGTM

**Comment by indutny** [comment]
Landed in d38f726d563454b4da7e05b5aaf34a354673a4a6, thank you!

**Comment by cristiankocza-sv** [comment]
Great, thanks.

**Pull request closed without merging**
